version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  db:
    image: postgres:13
    expose:
      - "5432"
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "williancard123@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5050:80"
    depends_on:
      - db
